name: Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        toolsets: [
          {host: [Linux, X64, self-hosted], preset: x64-linux-ninja-llvm},
          {host: [Linux, X64, self-hosted], preset: x64-linux-ninja-gcc},
        ]

    name: ${{matrix.toolsets.preset}} on ${{matrix.toolsets.host[0]}}
    runs-on: ${{matrix.toolsets.host}}

    steps:
    - name: Clone TheHighSeas
      uses: actions/checkout@v3
      with:
        lfs: 'true'
        path: ./thehighseas

    - name: Clone Toybox
      uses: actions/checkout@v3
      with:
        repository: HoneybunchBuilder/toybox
        lfs: 'true'
        path: ./toybox

    - name: Configure
      working-directory: ./thehighseas
      run: cmake --preset ${{matrix.toolsets.preset}} -DCOOK_ASSETS=OFF

    - name: Build Debug
      working-directory: ./thehighseas
      run: cmake --build --preset debug-${{matrix.toolsets.preset}}

    - name: Build RelWithDebInfo
      working-directory: ./thehighseas
      run: cmake --build --preset relwithdebinfo-${{matrix.toolsets.preset}}

    - name: Build Release
      working-directory: ./thehighseas
      run: cmake --build --preset release-${{matrix.toolsets.preset}}

  deploy:
    needs: build
    name: Deploy
    runs-on: [Linux, X64, self-hosted]
    steps:
    - name: Clone TheHighSeas
      uses: actions/checkout@v3
      with:
        lfs: 'true'
        path: ./thehighseas

    - name: Clone Toybox
      uses: actions/checkout@v3
      with:
        repository: HoneybunchBuilder/toybox
        lfs: 'true'
        path: ./toybox

    - name: Configure
      working-directory: ./thehighseas
      run: cmake --preset x64-linux-ninja-llvm -DFINAL=ON -DPROFILE_TRACY=OFF

    - name: Build Release
      working-directory: ./thehighseas
      run: cmake --build --preset release-x64-linux-ninja-llvm

    - uses: game-ci/steam-deploy@v1
      with:
        username: ${{ secrets.STEAM_USERNAME }}
        password: ${{ secrets.STEAM_PASSWORD }}
        configVdf: ${{ secrets.STEAM_CONFIG_VDF}}
        ssfnFileName: ${{ secrets.STEAM_SSFN_FILE_NAME }}
        ssfnFileContents: ${{ secrets.STEAM_SSFN_FILE_CONTENTS }}
        appId: ${{ secrets.STEAM_APP_ID }}
        buildDescription: v0.1.0
        rootPath: thehighseas/build/x64/linux-llvm
        depot2Path: Release
        releaseBranch: prerelease
