name: macOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  repository_dispatch:
    types: [macos-engine]

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        toolsets: [
          {host: [macOS, ARM64, self-hosted], preset: arm64-macos-ninja-llvm},
          # TODO: Figure out xcode build
          {host: [macOS, ARM64, self-hosted], preset: arm64-macos-ninja-gcc},
        ]

    name: ${{matrix.toolsets.preset}} on ${{matrix.toolsets.host[0]}}
    runs-on: ${{matrix.toolsets.host}}

    steps:
    - name: Clone TheHighSeas
      uses: actions/checkout@v3
      with:
        lfs: 'true'
        path: ./thehighseas

    - name: Clone Toybox
      uses: actions/checkout@v3
      with:
        repository: HoneybunchBuilder/toybox
        lfs: 'true'
        path: ./toybox

    - name: Configure
      working-directory: ./thehighseas
      run: cmake --preset ${{matrix.toolsets.preset}} -DCOOK_ASSETS=OFF

    - name: Build Debug
      working-directory: ./thehighseas
      run: cmake --build --preset debug-${{matrix.toolsets.preset}}

    - name: Build RelWithDebInfo
      working-directory: ./thehighseas
      run: cmake --build --preset relwithdebinfo-${{matrix.toolsets.preset}}

    - name: Build Release
      working-directory: ./thehighseas
      run: cmake --build --preset release-${{matrix.toolsets.preset}}

  deploy:
    needs: build
    name: Deploy
    runs-on: [macOS, ARM64, self-hosted]
    steps:
    - name: Clone TheHighSeas
      uses: actions/checkout@v3
      with:
        lfs: 'true'
        path: ./thehighseas

    - name: Clone Toybox
      uses: actions/checkout@v3
      with:
        repository: HoneybunchBuilder/toybox
        lfs: 'true'
        path: ./toybox

    - name: Configure
      working-directory: ./thehighseas
      run: cmake --preset arm64-macos-ninja-llvm -DFINAL=ON -DPROFILE_TRACY=OFF

    - name: Build Release
      working-directory: ./thehighseas
      run: cmake --build --preset release-arm64-macos-ninja-llvm

    - uses: game-ci/steam-deploy@v3
      with:
        username: ${{ secrets.STEAM_USERNAME }}
        configVdf: ${{ secrets.STEAM_CONFIG_VDF}}
        appId: ${{ secrets.STEAM_APP_ID }}
        buildDescription: v0.1.0
        rootPath: thehighseas/build/arm64/macos-llvm
        depot3Path: Release
        releaseBranch: prerelease