name: macOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        toolsets: [
          {host: [macOS, ARM64, self-hosted], preset: arm64-macos-ninja-llvm},
          # TODO: Figure out xcode build
          {host: [macOS, ARM64, self-hosted], preset: arm64-macos-ninja-gcc},
        ]

    name: ${{matrix.toolsets.preset}} on ${{matrix.toolsets.host[0]}}
    runs-on: ${{matrix.toolsets.host}}

    steps:
    - name: Clone TheHighSeas
      uses: actions/checkout@v3
      with:
        lfs: 'true'

    - name: Clone Toybox
      uses: actions/checkout@v3
      with:
        repository: HoneybunchBuilder/toybox
        lfs: 'true'

    - name: Configure
      working-directory: .
      run: cmake --preset ${{matrix.toolsets.preset}} -DCOOK_ASSETS=OFF -DTB_SOURCE_PATH=../toybox

    - name: Build Debug
      working-directory: .
      run: cmake --build --preset debug-${{matrix.toolsets.preset}}

    - name: Build RelWithDebInfo
      working-directory: .
      run: cmake --build --preset relwithdebinfo-${{matrix.toolsets.preset}}

    - name: Build Release
      working-directory: .
      run: cmake --build --preset release-${{matrix.toolsets.preset}}
